version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      # - ${backup_folder}:/backup
      - ${data}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${db_user:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${db_password:-root}
      MONGO_INITDB_DATABASE: app

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${db_user:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${db_password:-root}
